version: '3.8'

services:
  teamartemisse489:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teamartemisse489_app
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
  cinematch_ui:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.gradio
    container_name: cinematch_ui
    volumes:
      - ./data:/app/data
    ports:
      - "7860:7860"