defaults:
  - data: default
  - training: default
  - paths: local
  - logging: default
  - model: svd
  - _self_

project:
  name: teamartemisse489
  phase: phase_2

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}